version: "3.4"

services:
    pgAdmin:
        restart: always
        image: dpage/pgadmin4
        container_name: $PGADMIN_DEFAULT_HOST
        ports:
            - "8000:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
            PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
        volumes:
            - pgadmin:/var/lib/pgadmin

    postgres:
        restart: always
        image: postgres
        container_name: $POSTGRES_HOST
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
            POSTGRES_DB: $POSTGRES_DB
        volumes:
            - pgvol:/var/lib/postgresql/data
volumes:
    pgvol:
    pgadmin:
